Update deploy.yml

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -42,11 +42,21 @@ jobs:
       - name: Apply Terraform configuration
         run: terraform apply -auto-approve
 
+      - name: List directory contents
+        run: ls -l
+
       - name: Get EC2 Instance IP
         id: get-instance-ip
         run: |
           terraform output -raw public_ip > ec2_ip.txt
           cat ec2_ip.txt
+
+      - name: Check if IP file exists
+        run: |
+          if [ ! -f ec2_ip.txt ]; then
+            echo "File ec2_ip.txt not found!"
+            exit 1
+          fi
 
       - name: Debug EC2 IP
         run: |
